### ISSUE TITLE
Issue in moyaser 2.0.2

### ISSUE THREAD

**Issue by devm7mdibrahim** [moyasar/moyasar-flutter#19]
../../AppData/Local/Pub/Cache/hosted/pub.dev/moyasar-2.0.2/lib/src/widgets/network_icons.dart:8:18: Error: Cannot invoke a non-'const' constructor where a const expression is expected.
Try using a constructor or factory that is 'const'.

**Comment by Fghurayri** [comment]
Hey @devm7mdibrahim 👋

Can you please share more information about the issue?

Device (iOS/Android)
Physical/Simulator
OS Version
The `PaymentConfig` object used to initialize the widget

**Comment by devm7mdibrahim** [comment]
Hey @Fghurayri ,
Dart 2.19.4
Flutter 3.7.7
Android
Physical
13
final paymentConfig = PaymentConfig(
      publishableApiKey: PaymentStrings.publishableApiKey,
      amount: amount,
      description: 'order #1324',
      metadata: {'size': '250g'},
      applePay:
          ApplePayConfig(merchantId: PaymentStrings.merchantId, label: 'xxxxx', manual: false),
    );

**Comment by Fghurayri** [comment]
@devm7mdibrahim I'm not able to reproduce the issue. Looking at the path you've shared, the issue is most likely related to caching. Here are various ways to clearing the cache: https://stackoverflow.com/questions/49279379/how-to-clear-flutters-build-cache
