### ISSUE TITLE
some dependencies cause problems in v2.0.2

### ISSUE THREAD

**Issue by kururu-abdo** [moyasar/moyasar-flutter#20]
Error: Couldn't find constructor 'WebViewController'.
    final controller = WebViewController()

Error: Couldn't find constructor 'NavigationDelegate'.
      ..setNavigationDelegate(NavigationDelegate(onPageFinished: (pageUrl) {
                              ^^^^^^^^^^^^^^^^^^

**Comment by Fghurayri** [comment]
Hi @kururu-abdo, The issue you've reported can get solved by running `flutter clean` in the project. Please note that we just released a new version (`v2.0.3`) to support latest upgrades in the Flutter tooling and dependencies. Please upgrade the SDK and do `flutter clean` and let us know how it goes.

**Comment by kururu-abdo** [comment]
great 
thanks for response
